### ISSUE TITLE
Non-bootstrap and React 0.14

### ISSUE THREAD

**Issue by oyeanuj** [humanhighway/react-audio-player#1]
Hi @humanhighway, thanks for the library! I was wondering if there are any plans to move away from Bootstrap dependency as well as upgrade to React 0.14?

**Comment by humanhighway** [comment]
@oyeanuj , thanks for your response ! 
i created a es6 test branch last week and it upgraded to react 0.14.3 / es6  react component class, but still use react-bootstrap (0.27.0).
i think this branch it's easy to move away from react-bootstrap dependency maybe you can try, thanks!
